project:
  type: website
  output-dir: docs
website:
  repo-url: https://github.com/adrienb4475/TerminalEffects
  repo-actions: [source, issue]    
  site-url: https://adrienb4475.github.io/TerminalEffects/
format:
  html:
    toc: true
    echo: false
    fig-width: 7
    fig-height: 5
    code-fold: true
    code-tools: true
    warning: false