---
title: "Studying Terminal Effects in Northern Elephant Seals"
format:
  html:
    echo: false
    fig-width: 7
    fig-height: 5
    code-fold: true
    code-tools: true
    warning: false
    toc: true
editor: visual
---

```{r}
#| label: setup

library(tidyverse)
sealdat <- read_csv(here::here("data/Adrien Data Pull 2024_12_06.csv"))
cleanseal <- sealdat %>% filter(!is.na(animalID), !is.na(year), !is.na(observed), !is.na(tagsex), !is.na(firstobsbreed), !is.na(lastobsbreed), !is.na(calyear), !is.na(firstobsbreeddoy), !is.na(pupID), !is.na(pupsex), !is.na(yearborn), !is.na(age), !is.na(Wt)) #Clears out all the NA's from the sealdat set to have easier to understand data... less intimidating

#Pup sex vs Wt of pups/weans graph easy
library(ggplot2)

#ggplot(cleanseal, aes(x = Wt, y = age, color = pupsex)) +
 # geom_point(alpha = 0.5, size = 3) +  # Transparent points for less clutter
 # geom_smooth(method = "lm", se = FALSE) +  # Line of best fit 
 # labs(
  #  title = "Relationship between Weight and Age by Pup Sex",
   # x = "Weight",
   # y = "Age"
 # ) +
 # theme_minimal()

# #Making a Bargraph to start Comparing Age to sex, bleh made before
# ggplot(age_sealgraph, aes(x = factor(age), y = percent, fill = pupsex)) +
#   geom_bar(stat = "identity", position = "stack") +  # Stack bars
#   labs(
#     title = "Percentage Distribution by Age and Pup Sex",
#     x = "Age",
#     y = "Percentage"
#   ) +
#   theme_minimal()

    #Lets add to this by changing ages 18-21 as just old ages kinda how we did for age paper 

# age_sealgraph <- age_sealgraph %>% 
  # filter(!(age %in% c(18, 19, 20, 21)))
# ggplot(age_sealgraph, aes(x = factor(age), y = percent, fill = pupsex)) +
#   geom_bar(stat = "identity", position = "stack") +
#   geom_hline(yintercept = 50, linetype = "dotted", color = "black", size = 1) +
#   labs(
#     title = "Percentage Distribution by Age and Pup Sex",
#     x = "Age",
#     y = "Percentage"
#   ) +
#   theme_minimal()

#Age vs weight or their pup? wowww
ggplot(cleanseal, aes(x = age, y = Wt, color = pupsex)) +
  geom_point() +  # Scatter plot for weight vs. age
  geom_smooth(method = "loess", se = FALSE) +  # Line of best fit (linear regression)
  labs(
    title = "Looking at Weight Relation to Age of Mother",
    x = "Age", 
    y = "Weight"
  ) +
  theme_minimal()

#Average weight in the years? 
#FIRST find average weights
avg_weights <- cleanseal %>%
  group_by(age) %>%
   filter(!(age %in% c(18, 19, 20, 21))) %>%
  summarise(avg_weight = mean(Wt, na.rm = TRUE))
ggplot(avg_weights, aes(x = age, y = avg_weight)) +
  geom_point() +
  geom_smooth(method = "loess")


#Calculating lactation duration, can i make this cleaner somehow? 
cleanseal$firstobsbreed <- as.Date(cleanseal$firstobsbreed, format = "%Y-%m-%d")
cleanseal$lastobsbreed <- as.Date(cleanseal$lastobsbreed, format = "%Y-%m-%d")
cleanseal$lactation_duration <- as.numeric(difftime(cleanseal$lastobsbreed, cleanseal$firstobsbreed, units = "days"))
#OK.. lets get the avg lact dur? then rerun code above
avg_lactation <- cleanseal %>%
  group_by(age) %>%
  summarize(avg_lact = mean(lactation_duration, na.rm = TRUE))
#YASS THAT WORKSSS SOOO NOW LETS PLOT AGAINST THE MALE V F LACT PERIOD FOR AGES IN LAST YEARS OF LIFE 
ggplot(avg_lactation, aes(x= age, y= avg_lact)) +
         geom_point() +
         geom_smooth(method = "loess") +
         labs(
           title ="lactation duration in ages",
           x = "age", 
           y = "lact_duration")



```

Age seems to be calculated incorrectly

Both males and females included in data, not sure if we will need males

Figure out how to operate github pages

how can we see how many of those animals went on to have pups of their own?

```{r}
#Calculating Bio age
head(sealdat)
sealdat$animalID

sealdat %>% filter(animalID == 170, observed == 1) %>% 
  mutate(age = year - yearborn, 
         max_age = max(age), 
         bio_age = max_age - age) %>% view()
#Bioage clean
bioseal <- sealdat %>% filter(observed == 1, tagsex == "F") %>%
  group_by(animalID) %>%
  mutate(age = year - yearborn, 
         max_age = max(age), 
         bio_age = max_age - age) %>%
  filter(age > 2)

#Playing with bio pup sex
ggplot(bioseal, aes(x = Wt, y = age, color = pupsex)) +
  geom_point(alpha = 0.5, size = 3) +  # Transparent points for less clutter
  geom_smooth(method = "lm", se = FALSE) +  # Line of best fit 
  labs(
    title = "Relationship between Weight and Age by Pup Sex",
    x = "Weight",
    y = "Age"
  ) +
  theme_minimal()

#Looking at weights? Come back to 
ggplot(bioseal, aes(x = bio_age, y = Wt)) +
  geom_point() +
  geom_smooth(method = "loess")

#Calculate Lactation Duration
bioseal$firstobsbreed <- as.Date(bioseal$firstobsbreed, format = "%Y-%m-%d")
bioseal$lastobsbreed <- as.Date(bioseal$lastobsbreed, format = "%Y-%m-%d")
bioseal$lactation_duration <- as.numeric(difftime(bioseal$lastobsbreed, bioseal$firstobsbreed, units = "days"))
#Calculate Average lac for bio age 
avg_lactation <- bioseal %>%
  group_by(bio_age) %>%
  summarize(avg_lact = mean(lactation_duration, na.rm = TRUE))



```

OK.. I gotta clean stuff up fr

```{r}
#Lets restart.. lets look at our first idea! How do mothers in their last year haul out? Early or later.. 

ggplot(bioseal, aes(x = bio_age, y= firstobsbreeddoy))+
         geom_point()+ 
         geom_smooth(method = "loess") +
         labs( 
           title = "Do moms in their last year arrrive early?", 
           x = "Years before death", 
           y = "arrival time")
           

#Then we wanted to see lactation duration
ggplot(avg_lactation, aes(x= bio_age, y= avg_lact)) +
         geom_point() +
         geom_smooth(method = "loess") +
         labs(
           title ="lactation duration in ages",
           x = "age", 
           y = "lact_duration")

#Then Weights?
ggplot(bioseal, aes(x = bio_age, y = Wt)) +
  geom_point() +
  geom_smooth(method = "loess")

```

```{r}
#Random effect model
library(lme4)
lact_dat <- bioseal %>% 
  filter(!is.na(lactation_duration)) %>%
  mutate(year_fct = factor(year)) %>% 
           select(animalID, year_fct, bio_age, lactation_duration)
  
lact_mod <- glmer(
    lactation_duration ~ bio_age + (1 | animalID),
    lact_dat, 
    family = "binomial"
)

```
